[ui]
tabs_shown = true
tabs_auto_hide = false
tab_bar_position  = "top" # "top", "bottom", "left", "right"

hscrollbar_shown = true
hscrollbar_auto_hide = true

vscrollbar_shown = true
vscrollbar_auto_hide = true

menubar_shown = true
statusbar_shown = true


# Minimap settings
minimap_shown = true
minimap_auto_hide = true # Automatically hide minimap when not required
minimap_image = true # Show image preview in minimap
minimap_scale = 0.05 # Scale of the minimap relative to the main image
minimap_image_opacity = 0.75
minimap_location = "top-right" # "top-left", "top-right", "bottom-left", "bottom-right", "bottom-center", "top-center"
minimap_overlay_movable = true # Allow clicking on the minimap overlay to navigate the main view
minimap_clickable = true # Allow clicking on the minimap to navigate the main view

# Minimap overlay settings
minimap_overlay_color = "#44FFFFFF"
minimap_overlay_border = "#FF5050"
minimap_overlay_border_width = 50

[rendering]
dpr = { "eDP-1" = 1.25, "DP-5" = 1.0, "DP-7" = 1.0 } # Device Pixel Ratio for high-DPI displays; can be a single float value or a map of display names to DPR values

[behavior]
auto_reload = true
config_hot_reload = true

[keybindings]
open_file = "O"
close_file = "Ctrl+W"
toggle_tabs = "Ctrl+T"
toggle_fullscreen = "F11"
open_file_location = "Ctrl+L"
zoom_in = "="
zoom_out = "-"
rotate_clock = ">"
rotate_anticlock = "<"
fit_width = "Ctrl+Shift+W"
fit_height = "Ctrl+Shift+H"
scroll_left = "H"
scroll_right = "L"
scroll_up = "K"
scroll_down = "J"
toggle_minimap = "M"
flip_left = "Ctrl+H"
flip_right = "Ctrl+L"
flip_up = "Ctrl+K"
flip_down = "Ctrl+J"
reload_file = "F5"
open_containing_folder = "Ctrl+O"
toggle_menubar = "Ctrl+Shift+M"

# Go to the edges of the image
left_edge = "Shift+H"
right_edge = "Shift+L"
top_edge = "Shift+K"
bottom_edge = "Shift+J"

tab_next = "Ctrl+Tab"
tab_previous = "Ctrl+Shift+Tab"
tab_1 = "Alt+1"
tab_2 = "Alt+2"
tab_3 = "Alt+3"
tab_4 = "Alt+4"
tab_5 = "Alt+5"
tab_6 = "Alt+6"
tab_7 = "Alt+7"
tab_8 = "Alt+8"
tab_9 = "Alt+9"
tab_last = "Alt+0"


